name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files in gradle/wrapper
        run: ls -la gradle/wrapper

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "/home/ubuntu"
          strip_components: 2
          debug: true

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            # Ensure the directory exists
            sudo mkdir -p /opt/spring-plus
            
            # Remove old JAR file if it exists
            sudo rm -f /opt/spring-plus/spring-plus.jar
            
            # Find and move the new JAR file
            jar_file=$(find /home/ubuntu -name "*.jar" -type f -print -quit)
            if [ -n "$jar_file" ]; then
            sudo mv "$jar_file" /opt/spring-plus/spring-plus.jar
            
            # Ensure correct permissions
            sudo chown ubuntu:ubuntu /opt/spring-plus/spring-plus.jar
            sudo chmod 644 /opt/spring-plus/spring-plus.jar
            
            # Restart the service
            sudo systemctl restart spring-plus.service || sudo systemctl start spring-plus.service
            
            # Check the service status
            sudo systemctl status spring-plus.service
            
            # Show the last few lines of the application log
            sudo journalctl -u spring-plus.service -n 50 --no-pager
            else
            echo "No JAR file found in /home/ubuntu directory"
            exit 1
            fi
            
            # List contents of /opt/spring-plus for verification
            ls -l /opt/spring-plus