name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files in gradle/wrapper
        run: ls -la gradle/wrapper

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "/home/ubuntu"
          strip_components: 2
          debug: true

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            # Stop the existing application
            pkill -f spring-plus.jar || true
            
            # Move the new JAR file
            mv /home/ubuntu/*.jar /home/ubuntu/spring-plus.jar
            
            # Start the new application
            nohup java -jar /home/ubuntu/spring-plus.jar > /home/ubuntu/app.log 2>&1 &
            
            # Wait for the application to start
            sleep 10
            
            # Check if the application is running
            if pgrep -f spring-plus.jar > /dev/null
            then
              echo "Application started successfully"
            else
              echo "Failed to start the application"
              exit 1
            fi